name: 'xcode-version-setter'
description: 'set Build Numbers for Xcode projects'
inputs:
  style:  # id of input
    description: 'The style of build number to use (time, hextime)'
    required: true
    default: 'time'
  working-directory:
    description: 'The directory containing Xcode project'
    required: false
    default: './'
outputs:
  build-number: # id of output
    description: 'The build number that was set'
runs:
  using: 'node12'
  main: 'index.js'
